train:
  dataset_path: ProstateSSL:split=TRAIN:root=<PATH_TO_PROSTATE_DATASET>:split_csv=split/train.csv:mri_sequences=ax_t2wi,ax_adc,ax_dwi:random_axes=True:random_slices=True
  batch_size_per_gpu: 4
  num_workers: 4
  OFFICIAL_EPOCH_LENGTH: 4000  # adjust to ceil(num_patients / batch_size_per_gpu)
  saveckp_freq: 10
  img_size: 224
student:
  arch: glioma_vit_base
  use_mri_seq_embed: True
  img_wise_pos_embed: True
  patch_size: 14
  pretrained_weights: ""  # optionally set to a DINOv2 weight
teacher:
  init_with_student_weights: True
dino:
  head_n_prototypes: 8192
ibot:
  mask_per_channel: True
  head_n_prototypes: 8192
crops:
  global_crops_size: 224
  local_crops_size: 112
  global_crops_scale:
    - 0.5
    - 1.0
  local_crops_scale:
    - 0.2
    - 0.5
  crop_from_tumor_foreground: True
  intensity_aug: rc
  max_blur_radius: 1
  gamma_range:
    - 0.75
    - 1.5
semi_supervised:
  loss_weight: 0.0
optim:
  base_lr: 1e-4
  epochs: 200
  freeze_backbone_epochs: 0
  warmup_epochs: 20
  weight_decay: 0.04
  weight_decay_end: 0.4
  clip_grad: 3.0
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
evaluation:
  eval_period_iterations: 0  # disable classification eval for SSL
